/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export { ActiveModuleMembership } from './models/ActiveModuleMembership';
export type { ActiveSummaryPreviewRead } from './models/ActiveSummaryPreviewRead';
export type { AnswerFeedback } from './models/AnswerFeedback';
export type { AnswerForStudent } from './models/AnswerForStudent';
export type { AnswerSubmission } from './models/AnswerSubmission';
export type { AssessmentScopeResponse } from './models/AssessmentScopeResponse';
export type { AssetDownloadUrl } from './models/AssetDownloadUrl';
export { AssignMemberRequest } from './models/AssignMemberRequest';
export type { AssistantAvailabilityResponse } from './models/AssistantAvailabilityResponse';
export type { BenchmarkRead } from './models/BenchmarkRead';
export type { BriefSummaryContent } from './models/BriefSummaryContent';
export type { ConversationListItem } from './models/ConversationListItem';
export type { ConversationRead } from './models/ConversationRead';
export type { ConversationSaveSource } from './models/ConversationSaveSource';
export type { CreateAssessmentScopeRequest } from './models/CreateAssessmentScopeRequest';
export type { CreateModuleRequest } from './models/CreateModuleRequest';
export { CreateUserRequest } from './models/CreateUserRequest';
export { CurrentUserResponse } from './models/CurrentUserResponse';
export type { DetailedSummaryContent } from './models/DetailedSummaryContent';
export type { EarnedBadgeRead } from './models/EarnedBadgeRead';
export type { ExamPrepScopeSummary } from './models/ExamPrepScopeSummary';
export type { FolderCreateRequest } from './models/FolderCreateRequest';
export type { FolderUpdateRequest } from './models/FolderUpdateRequest';
export type { ForecastRead } from './models/ForecastRead';
export type { GamificationRead } from './models/GamificationRead';
export type { GlossaryEntryDetail } from './models/GlossaryEntryDetail';
export type { GlossaryEntryRead } from './models/GlossaryEntryRead';
export type { GlossaryFolderRead } from './models/GlossaryFolderRead';
export type { GlossarySourceReferenceRead } from './models/GlossarySourceReferenceRead';
export type { HTTPValidationError } from './models/HTTPValidationError';
export type { KeysetPage_MessageRead_ } from './models/KeysetPage_MessageRead_';
export type { LockedBadgeRead } from './models/LockedBadgeRead';
export type { MaintenanceRunRead } from './models/MaintenanceRunRead';
export { ManualEntryRequest } from './models/ManualEntryRequest';
export type { MembershipResponse } from './models/MembershipResponse';
export type { MessageRead } from './models/MessageRead';
export type { MistakeBankItem } from './models/MistakeBankItem';
export type { ModuleDetail } from './models/ModuleDetail';
export { ModuleMemberResponse } from './models/ModuleMemberResponse';
export type { ModuleResponse } from './models/ModuleResponse';
export { ModuleScheduleInput } from './models/ModuleScheduleInput';
export type { ModuleSchedulePreviewResponse } from './models/ModuleSchedulePreviewResponse';
export { ModuleSectionPreview } from './models/ModuleSectionPreview';
export type { ModuleSummary } from './models/ModuleSummary';
export type { PaginatedResponse_AssessmentScopeResponse_ } from './models/PaginatedResponse_AssessmentScopeResponse_';
export type { PaginatedResponse_ConversationListItem_ } from './models/PaginatedResponse_ConversationListItem_';
export type { PaginatedResponse_GlossaryEntryRead_ } from './models/PaginatedResponse_GlossaryEntryRead_';
export type { PaginatedResponse_MistakeBankItem_ } from './models/PaginatedResponse_MistakeBankItem_';
export type { PaginationMeta } from './models/PaginationMeta';
export type { PracticeAnswerFeedback } from './models/PracticeAnswerFeedback';
export type { PracticeAnswerRequest } from './models/PracticeAnswerRequest';
export type { PracticeAvailability } from './models/PracticeAvailability';
export type { PracticeItem } from './models/PracticeItem';
export type { PracticeOption } from './models/PracticeOption';
export type { PracticeResult } from './models/PracticeResult';
export type { PracticeSessionState } from './models/PracticeSessionState';
export type { ProgressDashboardRead } from './models/ProgressDashboardRead';
export type { ProgressItemRead } from './models/ProgressItemRead';
export type { ProgressModuleDetail } from './models/ProgressModuleDetail';
export type { ProgressModuleSummary } from './models/ProgressModuleSummary';
export type { QuizAttemptForStudent } from './models/QuizAttemptForStudent';
export type { QuizAttemptResult } from './models/QuizAttemptResult';
export type { QuizAttemptsSummary } from './models/QuizAttemptsSummary';
export type { QuizAvailabilityResponse } from './models/QuizAvailabilityResponse';
export type { QuizOptionForStudent } from './models/QuizOptionForStudent';
export type { QuizQuestionForStudent } from './models/QuizQuestionForStudent';
export type { ReapStuckRowsRequest } from './models/ReapStuckRowsRequest';
export type { RecapScopeRequest } from './models/RecapScopeRequest';
export type { ReconcileStorageRequest } from './models/ReconcileStorageRequest';
export type { RenameConversationRequest } from './models/RenameConversationRequest';
export type { ResetPasswordRequest } from './models/ResetPasswordRequest';
export { SaveHighlightRequest } from './models/SaveHighlightRequest';
export type { SaveResponse } from './models/SaveResponse';
export type { ScopeAvailabilityResponse } from './models/ScopeAvailabilityResponse';
export type { SectionAssetListResponse } from './models/SectionAssetListResponse';
export type { SectionAssetResponse } from './models/SectionAssetResponse';
export type { SectionDetail } from './models/SectionDetail';
export type { SectionListItem } from './models/SectionListItem';
export type { SectionMetadataDetail } from './models/SectionMetadataDetail';
export type { SectionMetadataPatchRequest } from './models/SectionMetadataPatchRequest';
export type { SectionWeekRead } from './models/SectionWeekRead';
export type { SendMessageRequest } from './models/SendMessageRequest';
export type { SendMessageResponse } from './models/SendMessageResponse';
export { SessionPatternEntry } from './models/SessionPatternEntry';
export { StartPracticeRequest } from './models/StartPracticeRequest';
export type { StatusResponse } from './models/StatusResponse';
export type { StudentAssetMeta } from './models/StudentAssetMeta';
export type { StudentMaterialMeta } from './models/StudentMaterialMeta';
export type { StudentSectionDetail } from './models/StudentSectionDetail';
export type { StudentSectionListItem } from './models/StudentSectionListItem';
export type { StudentSectionRead } from './models/StudentSectionRead';
export type { StudentSectionSummariesContent } from './models/StudentSectionSummariesContent';
export type { StudentSectionSummariesRead } from './models/StudentSectionSummariesRead';
export type { StudentSectionSummaryStates } from './models/StudentSectionSummaryStates';
export type { StudentSummarySlot } from './models/StudentSummarySlot';
export type { StudentSummarySlotState } from './models/StudentSummarySlotState';
export type { SummaryDefinition } from './models/SummaryDefinition';
export type { TargetGradeRequest } from './models/TargetGradeRequest';
export type { TopicMasteryRead } from './models/TopicMasteryRead';
export type { TranscriptMeta } from './models/TranscriptMeta';
export type { TranscriptProcessingStatus } from './models/TranscriptProcessingStatus';
export type { TranscriptProcessingStep } from './models/TranscriptProcessingStep';
export type { TranscriptProcessingSteps } from './models/TranscriptProcessingSteps';
export type { TranscriptSummariesRead } from './models/TranscriptSummariesRead';
export type { TrendPointRead } from './models/TrendPointRead';
export type { UpdateAssessmentScopeRequest } from './models/UpdateAssessmentScopeRequest';
export type { UpdateEntryRequest } from './models/UpdateEntryRequest';
export { UpdatePreferencesRequest } from './models/UpdatePreferencesRequest';
export type { UpdateSectionNotesRequest } from './models/UpdateSectionNotesRequest';
export type { UserResponse } from './models/UserResponse';
export type { ValidationError } from './models/ValidationError';

export { AdminService } from './services/AdminService';
export { AssessmentsService } from './services/AssessmentsService';
export { AssistantService } from './services/AssistantService';
export { ContentService } from './services/ContentService';
export { DefaultService } from './services/DefaultService';
export { GamificationService } from './services/GamificationService';
export { GlossaryService } from './services/GlossaryService';
export { MeService } from './services/MeService';
export { ModulesService } from './services/ModulesService';
export { ProgressService } from './services/ProgressService';
export { QuizService } from './services/QuizService';
export { StudentSummariesService } from './services/StudentSummariesService';
export { TranscriptsService } from './services/TranscriptsService';
